# Change these first
owner: mgmgpyaesonewin # Your GitHub organization or username, where this repository lives
repo: strapi-upptime # The name of this repository

sites:
  - name: Strapi Home Page
    url: https://preprod-content.wavemoney.io
  - name: Merchant APP (Core Config API)
    url: https://preprod-apim-gw.wavemoney.io/v2/merchant-api/merchant-core-config
  - name: Merchant APP (API Version API)
    url: https://preprod-apim-gw.wavemoney.io/v2/merchant-api/url-version/entity/merchant

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /strapi-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CMS Monitoring
  introTitle: "**Strapi** API Monitoring Status Page."
  introMessage: This is a Strapi API status page which uses **real-time** data from our [GitHub repository](https://github.com/mgmgpyaesonewin/strapi-upptime).Every incidents will recorded via GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
